language:
  python

services:
  - elasticsearch
  - docker

python:
  - 3.6

sudo: required

env:
  global:
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=datahq/deploy
    - DOCKER_IMAGE=datopian/specstore
    - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=specstore
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of dhq-specstore"
    - DEPLOY_GIT_EMAIL=dhq-deployer@null.void
    - DEPLOY_GIT_USER=dhq-deployer

install:
  - make install
  - curl -s https://raw.githubusercontent.com/datahq/deploy/master/apps_travis_script.sh > .travis.sh
  - bash .travis.sh script

script:
  - make test

before_script:
  - moto_server &
  - sleep 30
  - curl localhost:9200
  - curl localhost:5000

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
