language:
  python

python:
  - 3.6

install:
  - pip install --upgrade -r requirements.dev.txt
  - pip install https://github.com/datahq/assembler/archive/master.zip

script:
  - export
  - pylama specstore
  - python -m pytest tests -sv --cov=specstore

after_success:
  - coveralls
